version: "3.7"
services:
  mf-front:
    build:
      context: .
      dockerfile: .github/Dockerfile
    container_name: mf-front
    stdin_open: true
    expose:
      - 80
    healthcheck:
      test: "nc -z localhost 80"
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - mf


networks:
  ### You should create that network externally
  ### example: `docker network create -d bridge mf`
  mf:
    external: true
