---

name: Development

on:
  push:
    branches:
      - dev

jobs:
  deliver:
    runs-on: 
      - self-hosted
      - development
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup application on the dev
        run: |
          docker compose -f docker-compose.prod.yaml build
          docker compose -f docker-compose.prod.yaml down
          docker compose -f docker-compose.prod.yaml up -d