---

name: Development

on:
  push:
    branches:
      - ! "master"

jobs:
  # build:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout 
  #       uses: actions/checkout@v2

  #     - name: Login in the registry
  #       run: docker login ${REGISTRY_URL} ${REGISTRY_PASS} ${REGISTRY_PASS}

  #     - name: Build the app
  #       run: docker build -f .github/docker/Dockerfile --name ${REGISTRY_URL}/mf-front:${BRANCH_NAME} .
      
  #     - name: Push to registry
  #       run: docker push ${REGISTRY_URL}/mf-front:${BRANCH_NAME} 

  deliver:
    runs-on: self-hosted
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup application on the dev
        run: docker compose -f docker-compose.prod.yaml up --build -d